apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ecommerce-deployment
  labels:
    app: react-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-ecommerce
  template:
    metadata:
      labels:
        app: react-ecommerce
    spec:
      containers:
        - name: react-ecommerce
          image: kannandolmites/ecommerce:2
          ports:
            - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: react-ecommerce-service
spec:
  selector:
    app: react-ecommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort
            
